learning_log/urls.py
from django.contrib import admin
from django.urls import path, include,re_path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('learning_logs.urls')),
    path('users/', include('users.urls')),
]

learning_logs/urls.py
'''define URL patterns for leraning_logs app'''

from django.urls import path
from . import views


app_name = 'learning_logs'
urlpatterns = [
    # Main site
    path('', views.index, name='index'),
    # Topics list site
    path('topics/', views.topics, name='topics'),
    # Site of each topic entries
    path('topics/<int:topic_id>/', views.topic, name='topic'),
    # Adding new topic
    path('new_topic/', views.new_topic, name='new_topic'),
    # Adding new entries
    path('new_entry/<int:topic_id>/', views.new_entry, name='new_entry'),
    # Editing entry
    path('edit_entry/<int:entry_id>', views.edit_entry, name='edit_entry')
]

users/urls.py
'''Defines urls patters for users app'''

from django.urls import path, include

from . import views

app_name = 'users'

urlpatterns = [
    # Default authentication URL
    path('', include('django.contrib.auth.urls')),
    # Register site
    path('register/', views.register, name='register')
]

learning_logs/models.py
from django.db import models
from django.contrib.auth.models import User


class Topic(models.Model):
    '''Topic wchich user already learned'''

    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        '''Returns model representation as a string'''

        return self.text

class Entry(models.Model):
    '''Particular information about learning progress'''
    
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'entries'
    
    def __str__(self):
        '''return representaion of the model as a string'''
        if len(self.text) > 50:
            return f"{self.text[:50]}..."
        else:
            return self.text

users/models.py
from django.db import models

# Create your models here.

learning_logs/forms.py
from django import forms
from .models import Entry, Topic

class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['text']
        labels = {'text': ''}

class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text': ''}
        widgets = {'text': forms.Textarea(attrs={'cols': 80})}

    

learning_logs/views.py
from django.http import Http404
from django.shortcuts import get_object_or_404, render, redirect
from .models import Topic, Entry
from .forms import TopicForm, EntryForm
from django.contrib.auth.decorators import login_required

def index(request):
    '''Main website of learning_logs app'''

    return render(request, 'learning_logs/index.html')

@login_required
def topics(request):
    '''Display the list of topics'''

    topics = Topic.objects.filter(owner=request.user).order_by('date_added')
    context = {'topics': topics}
    return render(request, 'learning_logs/topics.html', context)

@login_required
def topic(request, topic_id):
    '''Display the list of each entry of the topic'''
    topic = get_object_or_404(Topic, id=topic_id)

    # Check whether the topic belong to this user
    _check_topic_owner(topic,request)

    entries = topic.entry_set.order_by('-date_added')
    context = {'topic': topic, 'entries': entries}

    return render(request, 'learning_logs/topic.html', context)

@login_required
def new_topic(request):
    '''Form to add a new Topic'''

    if request.method != 'POST':
        # If the request is not Post (it is GET) - create empty form
        form = TopicForm()
    else:
        # Data entered via POST method
        form = TopicForm(data=request.POST)
        if form.is_valid():
            new_topic = form.save(commit=False)
            new_topic.owner = request.user
            new_topic.save()
            return redirect('learning_logs:topics')
    
    # Display empty form
    context = {'form': form}
    return render(request, 'learning_logs/new_topic.html', context)

@login_required
def new_entry(request, topic_id):
    '''Add new entry to the topic'''

    topic = Topic.objects.get(id=topic_id)

    _check_topic_owner(topic,request)

    if request.method != 'POST':
        # Request is probably GET- so create an empty form
        form = EntryForm()
    else:
        # Request is POST - save the entry
        form = EntryForm(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            new_entry.save()
            return redirect('learning_logs:topic', topic_id = topic_id)

    # Dispaly the empty form
    context = {'topic': topic, 'form': form}
    return render(request, 'learning_logs/new_entry.html', context)

@login_required
def edit_entry(request, entry_id):
    '''Edit exisiting entry'''

    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic

    _check_topic_owner(topic,request)

    if request.method != 'POST':
        # If the method is not POST its probably GET
        form = EntryForm(instance=entry)
    else:
        # if the method is POST, update the entry
        form = EntryForm(instance=entry, data=request.POST)
        form.save()
        return redirect('learning_logs:topic', topic_id=topic.id)

    context = {'entry': entry, 'topic': topic, 'form': form}
    return render(request, 'learning_logs/edit_entry.html', context)

def _check_topic_owner(top,req):
    if top.owner != req.user:
        raise Http404

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm



def register(request):
    '''Registering the nuew user'''

    if request.method != 'POST':
        # Not POST so probably GET - create empty form
        form = UserCreationForm()
    else:
        # POST, so save the registration data
        form = UserCreationForm(data=request.POST)
        if form.is_valid:
            new_user = form.save()
            # Log the user in
            login(request, new_user)
            return redirect('learning_logs:index')

    # Display the empty form
    context = {'form': form}
    return render(request, 'registration/register.html', context)

learning_logs/templates/learning_logs/base.html
{% load bootstrap4 %}

<!doctype html>
<html lang="pl">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1,
        shrink-to-fit=no">
    <title>Learning Log</title>
  
    {% bootstrap_css %}
    {% bootstrap_javascript jquery='full' %}

  </head>

  <body>
    <nav class="navbar navbar-expand-md nabar-light bg-light mb-4 border">

        <a class="navbar-brand" href="{% url 'learning_logs:index' %}">
          Learning Log</a>

        <button class="navbar-toggler" type="button" data-toggle="collapse"
        data-target="#navbarCollapse" aria-controls="navbarCollapse"
        aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span></button>
      <div class="collapse navbar-collapse" id="navbarCollapse">
        <u1 class="navbar-nav mr-auto">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'learning_logs:topics' %}">
              Tematy</a>
          </li>
        </u1>
        <u1 class="navbar-nav ml-auto">
          {% if user.is_authenticated %}
            <li class="nav-item">
              <span class="navbar-text">Witaj, {{user.username}}!</span>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'users:logout' %}">Wyloguj</a>
            </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'users:register' %}">
              Zarejestruj</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'users:login' %}">Zaloguj</a>
          </li>
          {% endif %}
        </u1>
      </div>
    </nav>

    <main role="main" class="container">
      <div class="pb-2 mb-2 border-bottom">
        {% block page_header %}{% endblock page_header %}
      </div>
      <div>
        {% block content %}{% endblock content %}
      </div>
    </main>
  </body>

</html>

learning_logs/templates/learning_logs/edit_entry.html
{% extends "learning_logs/base.html" %}
{% load bootstrap4 %}

{% block page_header %}
    <p>
        <h2><a href="{% url 'learning_logs:topic' topic.id %}">
            {{topic}}
        </a></h2>
    </p>
    <p class="lead">Edycja wpisu:</p>
{% endblock page_header %}

{% block content %}

    <form action="{% url 'learning_logs:edit_entry' entry.id %}" method='post'
    class="form">
        {% csrf_token %}
        {% bootstrap_form form %}

        {% buttons %}
        <button name='submit' class="btn btn-primary">Zapisz zmiany</button>
        {% endbuttons %}
    </form>
{% endblock content %}

learning_logs/templates/learning_logs/index.html
{% extends "learning_logs/base.html" %}

{% block page_header %}
  <div class="jumbotron">
    <h1 class="display-3">Monitoruj postępy w nauce</h1>
    
    <p class="lead">Załóż konto, aby rozpocząc korzystanie z aplikacji 
        Learning Log oraz wyświetlić listę poznawanych tematów.
        Gdy nauczyć się czegoś nowego na dany temat, utwórz wpis
        podsumowujący to, czego się nauczyłeś.</p>

    <a class="btn btn-lg btn-primary" href="{% url 'users:register' %}"
      role="button">Zarejestruj konto &raquo;</a> 
  </div>
{% endblock page_header %}

learning_logs/templates/learning_logs/new_entry.html
{% extends "learning_logs/base.html" %}
{% load bootstrap4 %}

{% block page_header %}
    <p>
        <h2><a href="{% url 'learning_logs:topic' topic.id %}">
            {{topic}}
        </a></h2>
    </p>
    <p class="lead">Dodaj nowy wpis:</p>
{% endblock page_header %}


{% block content %}

    <form action="{% url 'learning_logs:new_entry' topic.id %}" method='post' 
    class="form">
        {% csrf_token %}
        {% bootstrap_form form %}

        {% buttons %}
        <button name='submit' class="btn btn-primary">Dodaj wpis</button>
        {% endbuttons %}
    </form>
{% endblock content %}

learning_logs/templates/learning_logs/new_topic.html
{% extends "learning_logs/base.html" %}
{% load bootstrap4 %}

{% block page_header %}
    <h2>Dodaj nowy temat</h2>
{% endblock page_header %}

{% block content %}
    
    <form action="{% url 'learning_logs:new_topic' %}" method='post' 
      class="form">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
        <button name='submit' class="btn btn-primary">Dodaj temat</button>
        {% endbuttons %}
    </form>

{% endblock content %}

learning_logs/templates/learning_logs/topic.html
{% extends 'learning_logs/base.html' %}


{% block page_header %}
    <h2>{{topic}}</h2>
{% endblock page_header %}

{% block content %}

    <p>
        <a href="{% url 'learning_logs:new_entry' topic.id %}">
            Dodaj nowy wpis
        </a>
    </p>
    
    {% for entry in entries %}
        <div class="card mb-3">
            <h4 class="card-header">
            {{ entry.date_added|date:'d M Y H:i' }}
                <small><span class="ml-2">
                    <a href="{% url 'learning_logs:edit_entry' entry.id %}">
                    Edytuj wpis
                    </span></a>
                </small>
            </h4>
            <div class="card-boody">   
                {{ entry.text|linebreaks }}
            </div>
        </div>
    {% empty %}
        <li>Nie ma jeszcze żadnego wpisu</li>
    {% endfor %}    

{% endblock content %}

learning_logs/templates/learning_logs/topics.html
{% extends "learning_logs/base.html" %}

{% block page_header %}
  <h1>Tematy</h1>
{% endblock page_header %}

{% block content %}
    <div class="border-bottom">
    <u1>
      {% for topic in topics %}
      <h5><li>
            <a href="{% url 'learning_logs:topic' topic.id %}">{{topic}}</a>
      </li></h5>
      {% empty %}
        <li><h5>Nie został jeszcze dodany żaden temat.</h5></li>
      {% endfor %}
    </u1>
    </div>

    <div>
      <h3><a href="{% url 'learning_logs:new_topic' %}">
        Dodaj nowy temat</a></h3>
    </div>   
{% endblock content %}